version: "3.7"

services:
  mongo:
    image: mongo:7.0.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    volumes:
      - db:/data/db
  backend:
    depends_on:
      - mongo
    build: ./backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3000:$NODE_PORT
    environment:
      - PORT=$NODE_PORT
    volumes:
      - ./backend:/app
      - node_modules:/app/node_modules

volumes:
  db:
  node_modules:
